CREATE TABLE `training`.`products` (
  `PRODUCT_ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCT_NAME` VARCHAR(50) NOT NULL,
  `DESCRIPTION` VARCHAR(256) NULL,
  `MRP` DOUBLE NOT NULL,
  `PRODUCT_CATEGORY` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`PRODUCT_ID`),
  UNIQUE INDEX `IDX_NAME` (`PRODUCT_NAME` ASC) VISIBLE);

