CREATE TABLE `training`.`tags` (
  `TAG_ID` INT NOT NULL AUTO_INCREMENT,
  `PRODUCT_ID` INT NOT NULL,
  `TAG` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TAG_ID`),
  UNIQUE INDEX `IDX_PROD_TAG` (`PRODUCT_ID` ASC, `TAG` ASC) VISIBLE,
  CONSTRAINT `fk_tags_1`
    FOREIGN KEY (`PRODUCT_ID`)
    REFERENCES `training`.`products` (`PRODUCT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);
