apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: audit-service
    version: v1
  name: audit-service
spec: 
  ports: 
    - 
      name: http
      port: 8077
      targetPort: 8077
  selector: 
    app: audit-service
    version: v1
  type: NodePort