--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: config-service
    version: v1
  name: config
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: config-service
      version: v1
  template: 
    metadata: 
      labels: 
        app: config-service
        version: v1
    spec: 
      containers: 
        - 
          image: "amitkch/config-service"
          imagePullPolicy: Always
          name: cloudconfig-service
          ports: 
            - 
              containerPort: 8090          
              name: http
              protocol: TCP
          env: 
          resources: 
            limits: 
              cpu: 400m
              memory: 768Mi
            requests: 
              cpu: 200m
              memory: 256Mi
