apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: discovery-service
    version: v1
  name: discovery-service
spec: 
  ports: 
    - 
      name: http
      port: 8761
      targetPort: 8761
  selector: 
    app: discovery-service
    version: v1
  type: NodePort