apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: gateway-service
    version: v1
  name: gateway-service
spec: 
  ports: 
    - 
      name: http
      port: 9091
      targetPort: 9091
  selector: 
    app: gateway-service
    version: v1
  type: NodePort