apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: product-service
    version: v1
  name: product-service
spec: 
  replicas: 1
  selector: 
    matchLabels: 
      app: product-service
      version: v1
  template: 
    metadata: 
      labels: 
        app: product-service
        version: v1
    spec: 
      containers: 
        - image: "amitkch/product-serviceo:1"
          imagePullPolicy: Always
          name: product-service
          env:
            - name:   zipkin.url
              value: "http://zipkin:9411"			
            - name: rabbitmq.host
              value: "rabbitmq-master"
            - name: rabbitmq.port
              value: "5672"
            - name: config.url
              value: "http://config-service:8090"
            - name: eureka.url
              value: "http://discovery-service:8761/eureka"
          resources:
            requests:
                memory: "256Mi"
                cpu: "200m"
            limits:
                memory: "768Mi"
                cpu: "400m"                
