version: "3.3"

services:
  db1:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'training'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dbuser'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'passw0rd'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'passw0rd'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 13306:3306
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted
    tmpfs:
      - /var/lib/mysql:rw

networks:
  default:
    external:
      name: bootcamp_nw
