CREATE TABLE `employees` (
  `EMPLOYEE_ID` int NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` varchar(45) NOT NULL,
  `LAST_NAME` varchar(45) NOT NULL,
  `DEPARTMENT` varchar(100) NOT NULL,
  `EXPERIANCE` int NOT NULL,
  PRIMARY KEY (`EMPLOYEE_ID`),
  UNIQUE KEY `IDX_NAME` (`FIRST_NAME`,`LAST_NAME`);
);

